### ISSUE TITLE
Key ordering differs from jupyter/notebook

### ISSUE THREAD

**Issue by jdfreder** [nteract/commutable#25]
JSON does not guarantee the order of keys.  The order of keys is dependent on the implementation of the JSON parser being used.  Jupyter notebook uses Python's JSON parser while nteract uses V8's Javascript JSON parser. 

To see the issue refer to the following diff: https://github.com/jdfreder/_test/compare/nb

**Comment by rgbkrk** [comment]
This will irritate users trying to go between both frontends who are using git. That itself is a problem more generally because the on disk format is JSON. I'll throw my hands up and say ouch to that one.

As for actions to take, I am strongly against there being a strict ordering on JavaScript Object keys, spec wise. Maintaining that would be a hassle and I'm not sure that we can really say it's a simple json format anymore if it's an ordered set of keys.

However, there are bits of comparison where the above diff can get closer without being too burdensome:

* Multiline strings for `toJS` #12 
* `JSON.stringify` should set the space argument to 2 (the last argument)

Where we will continue to differ:

* Unspecced yet implemented and widely used metadata on the jupyter/notebook implementation
* Extensions that introduce their own metadata into the notebook

**Comment by betatim** [comment]
Some knowledge related to `diff`ing: https://gist.github.com/takluyver/bc8f3275c7d34abb68bf

You can register a custom converter for notebooks like this:
```
echo "*.ipynb diff=ipynb" >> .gitattributes
git config diff.ipynb.textconv nbflatten.py
```
which will call `nbflatten.py` (get it from the gist) or implement your own and enjoy more useful diffs.

**Comment by betatim** [comment]
I am 👎  on imposing an order on the keys. If there are a few simple (and easy to maintain) things that can be done to make it less annoying to text diff notebooks we should do them. Otherwise we are just annoying people :trollface:, which is never nice.

The real solution is to create `differact a.ipynb b.ipynb` 😀

**Comment by jdfreder** [comment]
> The real solution is to create differact a.ipynb b.ipynb

:+1:

**Comment by rgbkrk** [comment]
We've fixed up some of the above and this package is now inside of nteract/nteract as `@nteract/commutable` on npm.

**Comment by williamstein** [comment]
What do you actually use when exporting an ipynb Javascript object to a string/file?  I use

    json_stable(obj, {space:1})

where json_stable is from https://github.com/substack/json-stable-stringify

**Comment by rgbkrk** [comment]
Neat!

We use `JSON.stringify(notebook, null, 2);` where `notebook` is a v4 notebook:

* https://github.com/nteract/nteract/blob/6383c940f38017088ff3612c2ff3f2d072055983/packages/commutable/src/index.js#L73

**Comment by williamstein** [comment]
1. Using jsonstable is better because it is stable -- the output will be the same over time and across machines.  I think it's also exactly the same as the classic notebook in terms of ordering.  The only difference I saw in my testing is that empty lists are `[]` in classic, but `[\n]` in jsonstable.

2. Using 1 instead of 2 for the indent level also makes things consistent with the classic notebook (and ours).

**Comment by rgbkrk** [comment]
We can certainly switch to those.
