### ISSUE TITLE
Try out withMutations for our long nested operations

### ISSUE THREAD

**Issue by rgbkrk** [nteract/commutable#51]
We have a lot of deeply chained operations when we're loading a notebook (for the multiline-cleaning for instance) which seems to take a while. Could we get better performance by using `withMutations`? That or doing the conversion in vanilla JS _then_ creating the Immutable document.

**Comment by philpl** [comment]
Just to quickly leave my 2 cents here,

It looks like there's a *lot* of unnecessary, consecutive `set` and `setIn` operations here. Wrapping them in `withMutations` or `asMutable`/`asImmutable` is a quick win.

I wouldn't do the operations in vanilla JS unless it's absolutely necessary, since in that case all the advantages of immutability and Immutable.js are lost before the conversion. Since most of the operations here are definitely benefitting from Immutable.js's methods, easy API and so on, it would be good to keep it this way.

If performance is a concern, the code could keep everything as a mutable until the very end maybe? But we should be careful, since a lot of mutable-related things in Immutable.js are not well documented and sometimes even buggy.

**Comment by rgbkrk** [comment]
The reason I talk about vanilla JS is that the _initial load_ of the notebook document is when we do a bunch of permutations to build our in-memory model. It only happens once and then _immediately_ we want the Immutable.js structure. It's definitely what makes loading nteract fairly slow (in addition to all the blocking `require`s)

**Comment by rgbkrk** [comment]
Alternatively, we could be using [`mori` + their transducers](https://github.com/swannodette/mori#transducers) or @jlongster's [transducers.js](https://github.com/jlongster/transducers.js) so that we keep the fluent style yet get better performance.

**Comment by rgbkrk** [comment]
All done in the `@nteract/commutable` library!
